# EGX30 Constituents Fundamental Data Scrapping

In [1]:
from time import sleep
from re import sub
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

from bs4 import BeautifulSoup

import warnings
warnings.filterwarnings('ignore')

%load_ext autoreload
%autoreload 2

In [182]:
class FundamentalsLoader():
    def __init__(self, chromedriver_path, wait_period=10, freq='annually'):
        options = Options()
        options.page_load_strategy = 'none'
        self.DRIVER = webdriver.Chrome(, options=options)
        self.WAIT_PERIOD = wait_period
        self.WAIT = WebDriverWait(self.DRIVER, wait_period)
        self.FREQ = freq
        self.ANNUAL_XPATH = '//*[@id="leftColumn"]/div[8]/div[1]/a[1]'
        
    def load_page(self, asset_url_id, statement):
        url = f'https://www.investing.com/equities/{asset_url_id}-{statement}'
        self.DRIVER.get(url)
        self.WAIT.until(EC.url_to_be(url))
        sleep(5)
        if statement != 'ratios' and self.FREQ == 'annually':
            annual_button = self.DRIVER.find_element(By.XPATH, self.ANNUAL_XPATH)
            self.DRIVER.execute_script("arguments[0].click();", annual_button)
            sleep(5)
    
    def get_val(self, td):
        # numeric columns store their value in this attribute in addition to text
        val = td.get('data-format-value')
        if val:
            try:
                return np.float64(val)
            except ValueError:
                return np.nan
        return td.text
    
    def get_data(self, asset_id, asset_url_id, statement):
        self.load_page(asset_url_id, statement)
        soup = BeautifulSoup(self.DRIVER.page_source, 'html.parser')
        if statement == 'ratios':
            table = soup.find('table', id='rrTable')
        else:
            table = soup.find('div', id='rrtable')

        columns = [x.text.lower().replace(' ', '').rstrip('*') for x in table.find_all('th')]
        if statement=='cash-flow':
            columns=columns[:5]
        
        if statement != 'ratios':
            columns = ['metric']+[datetime.datetime.strptime(x, '%Y%d/%m').date() for x in columns[1:]]
        
        rows = []
        for tr in table.find_all('tr'):
            row = [self.get_val(x) for x in tr.find_all('td')]
            if len(row)!=len(columns):
                continue
            rows.append(row)

        df = pd.DataFrame(columns=columns, data=rows)
        df['statement'] = [statement,]*df.shape[0]
        df['asset'] = [asset_id,]*df.shape[0]
        
        print(f'Financial Statements of {asset_id} are downloaded successfully!')
        return df

In [1]:
assets = pd.read_csv('C:/investment/EGX/data/egx30_constituents.csv')
assets.head()

NameError: name 'pd' is not defined

In [ ]:
chromedriver_path = "C:/Users/AbdullahBahi/.wdm/drivers/chromedriver/win64/125.0.6422.78/chromedriver.exe"
fl = FundamentalsLoader(chromedriver_path=chromedriver_path)

statements = ['income-statement', 'balance-sheet', 'cash-flow']
financial_statements = pd.DataFrame()
for asset_id, asset_url_id in zip(assets.symbol, assets.url_id):
    for statement in statements:
        data = fl.get_data(asset_id=asset_id, asset_url_id=asset_url_id, statement=statement)
        financial_statements = pd.concat([financial_statements, data], ignore_index=True)

page loaded

Exception ignored in: <function Service.__del__ at 0x000002A3D2AB3AF0>
Traceback (most recent call last):
  File "C:\Users\AbdullahBahi\anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 178, in __del__
    self.stop()
  File "C:\Users\AbdullahBahi\anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 153, in stop
    self.send_remote_shutdown_command()
  File "C:\Users\AbdullahBahi\anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 137, in send_remote_shutdown_command
    if not self.is_connectable():
  File "C:\Users\AbdullahBahi\anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 124, in is_connectable
    return utils.is_connectable(self.port)
  File "C:\Users\AbdullahBahi\anaconda3\lib\site-packages\selenium\webdriver\common\utils.py", line 109, in is_connectable
    socket_ = socket.create_connection((host, port), 1)
  File "C:\Users\AbdullahBahi\anaconda3\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
KeyboardInterrupt:

NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=125.0.6422.113)
Stacktrace:
	GetHandleVerifier [0x00007FF64B101F22+60322]
	(No symbol) [0x00007FF64B07CE99]
	(No symbol) [0x00007FF64AF37EBA]
	(No symbol) [0x00007FF64AF0D5A5]
	(No symbol) [0x00007FF64AFB36B7]
	(No symbol) [0x00007FF64AFCB331]
	(No symbol) [0x00007FF64AFABFC3]
	(No symbol) [0x00007FF64AF79617]
	(No symbol) [0x00007FF64AF7A211]
	GetHandleVerifier [0x00007FF64B41946D+3301613]
	GetHandleVerifier [0x00007FF64B463693+3605267]
	GetHandleVerifier [0x00007FF64B459410+3563664]
	GetHandleVerifier [0x00007FF64B1B42F6+790390]
	(No symbol) [0x00007FF64B0874DF]
	(No symbol) [0x00007FF64B0833D4]
	(No symbol) [0x00007FF64B083562]
	(No symbol) [0x00007FF64B072F6F]
	BaseThreadInitThunk [0x00007FF806B37344+20]
	RtlUserThreadStart [0x00007FF8079E26B1+33]

In [177]:
financial_statements

,metric,2023-12-31 00:00:00,2022-12-31 00:00:00,2021-12-31 00:00:00,2020-12-31 00:00:00,statement,asset
0,Net Interest Income,8929.45,-,3615.91,3106.58,income-statement,ADIB
1,"Interest Income, Bank",19538.95,-,8197.87,7147.76,income-statement,ADIB
2,Total Interest Expense,10609.5,-,4581.96,4041.18,income-statement,ADIB
3,Loan Loss Provision,1633.83,-,175.59,444.29,income-statement,ADIB
4,Net Interest Income After Loan Loss Provision,7295.62,-,3440.32,2662.29,income-statement,ADIB
...,...,...,...,...,...,...,...
87,Beginning Cash Balance,10453.74,5601.06,-,-,cash-flow,ADIB
88,Ending Cash Balance,49392.14,14809.23,-,-,cash-flow,ADIB
89,Free Cash Flow,-,-,-,-,cash-flow,ADIB
90,Free Cash Flow Growth,-,-,-,-,cash-flow,ADIB
91,Free Cash Flow Yield,32.81,-,-,-,cash-flow,ADIB

In [145]:
fl = FundamentalsLoader()
IS = fl.get_data(asset='abou-kir-fertilizers', statement='income-statement')
IS

page loaded

,periodending:,202330/06,202230/06,202130/06,202030/06
0,Total Revenue,21557.86,16330.93,8839.41,7881.74
1,Revenue,21557.86,16330.93,8839.41,7881.74
2,"Other Revenue, Total",-,-,-,-
3,"Cost of Revenue, Total",8938.19,5703.32,4932.57,4997.39
4,Gross Profit,12619.67,10627.62,3906.84,2884.34
5,Total Operating Expenses,9821.03,6532.55,5498.36,5560.65
6,"Selling/General/Admin. Expenses, Total",1033.83,705.81,570.13,539.68
7,Research & Development,-,-,-,-
8,Depreciation / Amortization,-,-,11.12,11.37
9,Interest Expense (Income) - Net Operating,-11.63,-12.24,-1.47,-
10,Unusual Expense (Income),-,-,-,-
11,"Other Operating Expenses, Total",-139.35,135.66,-2.88,12.21
12,Operating Income,11736.83,9798.39,3341.06,2321.08
13,"Interest Income (Expense), Net Non-Operating",-,-,819.15,948.43
14,Gain (Loss) on Sale of Assets,24.85,0.588,12.24,1.08
15,"Other, Net",-6798.55,-1770.59,-989.28,138.08
16,Net Income Before Taxes,18510.53,11568.39,4318.1,3408.68
17,Provision for Income Taxes,3870.3,2514.25,802.09,713.8
18,Net Income After Taxes,14640.23,9054.14,3516.01,2694.89
19,Minority Interest,-,-,-,-
20,Equity In Affiliates,-,-,-,-
21,U.S GAAP Adjustment,-,-,-,-
22,Net Income Before Extraordinary Items,14640.23,9054.14,3516.01,2694.89
23,Total Extraordinary Items,-,-,-,-
24,Net Income,14640.23,9054.14,3516.01,2694.89
25,Total Adjustments to Net Income,-2413.57,-1480.74,-577.21,-
26,Income Available to Common Excluding Extraordi...,12226.66,7573.4,2938.8,2694.89
27,Dilution Adjustment,2413.57,1480.74,577.21,-
28,Diluted Net Income,12226.66,7573.4,2938.8,2694.89
29,Diluted Weighted Average Shares,1261.88,1261.88,1261.88,1261.88
30,Diluted EPS Excluding Extraordinary Items,9.69,6,2.33,2.14
31,DPS - Common Stock Primary Issue,5,3,1.3,1.2
32,Diluted Normalized EPS,9.16,5.73,2.13,2.13

In [152]:
import datetime

In [155]:
IS.columns = [datetime.datetime.strptime(x, '%Y%d/%m') for x in IS.columns[1:]]

[datetime.datetime(2023, 6, 30, 0, 0),
 datetime.datetime(2022, 6, 30, 0, 0),
 datetime.datetime(2021, 6, 30, 0, 0),
 datetime.datetime(2020, 6, 30, 0, 0)]

In [146]:
fl = FundamentalsLoader()
bs = fl.get_data(asset='abou-kir-fertilizers', statement='balance-sheet')
bs

page loaded

,periodending:,202330/06,202230/06,202130/06,202030/06
0,Total Current Assets,27317.37,16633.76,9123.56,7643.73
1,Cash and Short Term Investments,23921.94,14201.84,7225.48,6069.62
2,Cash,-,-,0.19,0.39
3,Cash & Equivalents,17445.8,2933.8,625.63,587.5
4,Short Term Investments,6476.14,11268.04,6599.85,5481.72
5,"Total Receivables, Net",664.34,668.72,578.61,258.57
6,"Accounts Receivables - Trade, Net",259.88,190.69,159.28,77.47
7,Total Inventory,2142.82,1563.96,1282.39,1276.05
8,Prepaid Expenses,1.45,2.06,36.3,37.33
9,"Other Current Assets, Total",586.82,197.19,37.08,2.16
10,Total Assets,35425.01,22372.47,10847.84,9311.64
11,"Property/Plant/Equipment, Total - Net",1583.85,1515.61,1383.3,1334.41
12,"Property/Plant/Equipment, Total - Gross",4303.79,4117.16,3950.72,3794.84
13,"Accumulated Depreciation, Total",-2719.94,-2601.55,-2567.42,-2460.43
14,"Goodwill, Net",-,-,-,-
15,"Intangibles, Net",-,-,-,-
16,Long Term Investments,6523.79,4223.11,340.98,333.5
17,Note Receivable - Long Term,383.5,450.36,417.78,-
18,"Other Long Term Assets, Total",-,-0,-,-
19,"Other Assets, Total",8562.41,12388.13,7342.26,-
20,Total Current Liabilities,5713.68,4074.13,2149.62,2089.76
21,Accounts Payable,582.35,539.61,455.69,483.9
22,Payable/Accrued,-,-,-,-
23,Accrued Expenses,956.17,67.41,23.36,-
24,Notes Payable/Short Term Debt,22.65,-,-,17.18
25,Current Port. of LT Debt/Capital Leases,1.29,0.104,0.046,25.61
26,"Other Current liabilities, Total",4151.21,3467,1670.52,1563.07
27,Total Liabilities,6049.61,4566.08,2487.24,2511.91
28,Total Long Term Debt,-,-,-,0.05
29,Long Term Debt,-,-,-,0.05
30,Capital Lease Obligations,-,-,-,-
31,Deferred Income Tax,156.89,153.71,121.67,119.15
32,Minority Interest,-,-,-,-
33,"Other Liabilities, Total",133.74,338.24,215.91,302.95
34,Total Equity,29375.41,17806.39,8360.61,6799.73
35,"Redeemable Preferred Stock, Total",-,-,-,-
36,"Preferred Stock - Non Redeemable, Net",-,-,-,-
37,"Common Stock, Total",1892.81,1892.81,1892.81,1892.81
38,Additional Paid-In Capital,-,-,-,-
39,Retained Earnings (Accumulated Deficit),15600.5,12020.25,6457.88,4906.92
40,Treasury Stock - Common,-,-,-,-
41,ESOP Debt Guarantee,-,-,-,-
42,Unrealized Gain (Loss),-,-,-,-
43,"Other Equity, Total",11882.1,3893.33,9.91,-
44,Total Liabilities & Shareholders' Equity,35425.01,22372.47,10847.84,9311.64
45,Total Common Shares Outstanding,1261.88,1261.88,1261.88,1261.88
46,Total Preferred Shares Outstanding,-,-,-,-

In [147]:
fl = FundamentalsLoader()
cf = fl.get_data(asset='delta-sugar', statement='cash-flow')
cf

page loaded

,periodending:,202331/12,202231/12,202131/12,202031/12
0,Net Income/Starting Line,1591.65,850.41,385.01,-253.95
1,Cash From Operating Activities,360.28,859.2,419.16,870.42
2,Depreciation/Depletion,52.69,61.9,63.63,66.85
3,Amortization,-,-,-,-
4,Deferred Taxes,-,-,-,-
5,Non-Cash Items,-298.19,-28.11,39.07,75.45
6,Cash Receipts,-,-,-,-
7,Cash Payments,-,-,-,-
8,Cash Taxes Paid,-,-,-,-
9,Cash Interest Paid,-,21.4,80.49,126.69
10,Changes in Working Capital,-985.87,-25,-68.55,982.07
11,Cash From Investing Activities,419.44,271.33,29.1,28.6
12,Capital Expenditures,-54.38,-22.6,-20.03,-26.82
13,"Other Investing Cash Flow Items, Total",473.81,293.93,49.13,55.42
14,Cash From Financing Activities,-266.72,-241.93,-457.61,-895.65
15,Financing Cash Flow Items,-5.45,-21.4,-80.49,-126.69
16,Total Cash Dividends Paid,-477.9,-86.3,-,-39.67
17,"Issuance (Retirement) of Stock, Net",-,-,-,-
18,"Issuance (Retirement) of Debt, Net",216.63,-134.23,-377.12,-729.29
19,Foreign Exchange Effects,-,224.56,1.87,-
20,Net Change in Cash,512.99,888.6,-9.35,3.38
21,Beginning Cash Balance,958.38,69.77,79.13,-
22,Ending Cash Balance,1471.37,958.38,69.77,-
23,Free Cash Flow,560.74,848.17,204.78,-
24,Free Cash Flow Growth,-33.89,314.18,-77.89,-
25,Free Cash Flow Yield,2.42,27.11,19.51,-

In [148]:
fl = FundamentalsLoader()
ratios = fl.get_data(asset='delta-sugar', statement='ratios')
ratios

page loaded

                                  name  company industry
0
1                        P/E Ratio TTM     7.13    10.57
2                   Price to Sales TTM     0.99     2.87
3               Price to Cash Flow MRQ        -     10.5
4          Price to Free Cash Flow TTM     7.82    43.85
5                    Price to Book MRQ     3.52     6.73
6           Price to Tangible Book MRQ     3.47     6.73
7
8                     Gross margin TTM    22.9%    32.84
9                     Gross Margin 5YA   13.62%    32.52
10                Operating margin TTM   19.49%    26.78
11                Operating margin 5YA   11.51%    17.85
12                   Pretax margin TTM   23.31%    33.98
13                   Pretax margin 5YA   10.96%    21.39
14               Net Profit margin TTM    17.9%    26.72
15               Net Profit margin 5YA    8.64%     16.1
16
17                   Revenue/Share TTM    58.32    20.55
18                       Basic EPS ANN      9.1     2.88
19                     Diluted EPS ANN      9.1     2.88
20                Book Value/Share MRQ    16.36     6.92
21       Tangible Book Value/Share MRQ    16.36     6.64
22                      Cash/Share MRQ    12.81     3.65
23                 Cash Flow/Share TTM     7.69     2.82
24
25                Return on Equity TTM   55.74%    53.02
26                Return on Equity 5YA   15.98%     27.5
27                Return on Assets TTM   30.91%    20.11
28                Return on Assets 5YA    12.5%    15.05
29            Return on Investment TTM   72.03%    35.38
30            Return on Investment 5YA   22.09%    25.57
31
32      EPS(MRQ) vs Qtr. 1 Yr. Ago MRQ  -32.76%    29.14
33       EPS(TTM) vs TTM 1 Yr. Ago TTM   34.97%    95.11
34               5 Year EPS Growth 5YA   34.14%    16.45
35   Sales (MRQ) vs Qtr. 1 Yr. Ago MRQ   -4.39%    17.49
36    Sales (TTM) vs TTM 1 Yr. Ago TTM  108.07%     31.5
37             5 Year Sales Growth 5YA   27.96%     9.94
38  5 Year Capital Spending Growth 5YA   13.97%   -17.61
39
40                     Quick Ratio MRQ     0.57      0.7
41                   Current Ratio MRQ      1.4      1.2
42               LT Debt to Equity MRQ        -     6.46
43            Total Debt to Equity MRQ    9.23%    27.86
44                          Efficiency
45                  Asset Turnover TTM     1.73     0.98
46              Inventory Turnover TTM     3.52     5.72
47                Revenue/Employee TTM        -        -
48             Net Income/Employee TTM        -        -
49             Receivable Turnover TTM        -     55.3
50
51                  Dividend Yield ANN    3.53%     5.59
52      Dividend Yield 5 Year Avg. 5YA    5.39%      8.8
53            Dividend Growth Rate ANN     410%     9.02
54                    Payout Ratio TTM   45.56%    67.83